name: CI-CD Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 836479503728.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: myapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Login to ECR (GitHub runner side)
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ECR_REGISTRY

      # 4️⃣ Build Image
      - name: Build Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} ./app

      # 5️⃣ Tag Image
      - name: Tag Image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      # 6️⃣ Push Image
      - name: Push Image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      # 7️⃣ Deploy to EC2 (NO AWS LOGIN HERE)
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

            echo "Deploying image..."

            kubectl set image deployment/myapp \
            myapp=836479503728.dkr.ecr.ap-south-1.amazonaws.com/myapp:${{ github.sha }}

            echo "Deployment updated successfully"

            exit 0
